{
 "title": "Tweeter-API Dash",
 "time": { "from": "2022-02-15T21:08:32.436Z", "to": "2022-02-16T09:08:32.436Z" },
 "panels": [
  {
   "title": "Client Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_client_requests_seconds_sum[5m])\n"
    }
   ]
  },
  {
   "title": "Total Server Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "yaxes": [
    { "format": "cpm" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{uri=\"/tweets/date\", status=\"200\",job=\"spring-monitoring\",outcome=\"SUCCESS\"}[5m])\n",
     "legendFormat": "Count Tweets by Date and Hour "
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{uri=\"/users-with-most-followers\",status=\"200\",job=\"spring-monitoring\",outcome=\"SUCCESS\"}[5m])\n",
     "legendFormat": "/users-with-most-followers"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{uri=\"/tweets/lang\",status=\"200\",job=\"spring-monitoring\",outcome=\"SUCCESS\"}[5m])\n",
     "legendFormat": "Count Tweets by HashTag and Lang"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{uri=\"/tweets/date\",outcome=\"SERVER_ERROR\"}[5m])\n",
     "legendFormat": "Get count tweet by date (Errors)"
    },
    {
     "expr": "rate(http_server_requests_seconds_count{uri=\"/users-with-most-followers\", outcome=\"SERVER_ERROR\"}[5m])\n",
     "legendFormat": "/users-with-most-followers(Errors)"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{uri=\"/tweets/lang\", outcome=\"SERVER_ERROR\"}[5m])\n",
     "legendFormat": "Get count tweet by lang (Errors)"
    }
   ]
  }
 ]
}