{
 "title": "Tweeter-API Dash",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{uri=\"/get-count-tweets\", outcome=\"CLIENT_ERROR\"}[5m])\n",
     "legendFormat": "/get-count-tweets"
    },
    {
     "expr": "rate(http_server_requests_seconds_count{uri=\"/users-with-most-followers\", outcome=\"CLIENT_ERROR\"}[5m])\n",
     "legendFormat": "/users-with-most-followers"
    }
   ]
  },
  {
   "title": "Client Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(http_client_requests_seconds_count[5m])\n"
    }
   ]
  },
  {
   "title": "Total Server Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{uri=\"/get-count-tweets\"}[5m])\n",
     "legendFormat": "/get-count-tweets"
    },
    {
     "expr": "rate(http_server_requests_seconds_count{uri=\"/users-with-most-followers\"}[5m])\n",
     "legendFormat": "/users-with-most-followers"
    }
   ]
  }
 ]
}